### ISSUE TITLE
Release 4.1.0 tag/zip doesn't match?

### ISSUE THREAD

**Issue by jrbp** [libkeepass/pykeepass#398]
Hi I'm tracking down an issue with using keepmenu (which depends on pykeepass) installed through the nix package manager.
I'm still getting https://github.com/libkeepass/pykeepass/issues/390, despite it appearing that 4.1.0 was installed.

I believe the nixpkgs package uses the zip file from github generated for the release.
In this repo if I download the zip file listed under the 4.1.0 release it seems to not have the modified version.py file, and furthermore the pyproject.toml still lists the version as 4.0.7. If I select v4.1.0 under the branches/tags I also don't see the updated source and github gives the warning "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

So while the tag exists it seems like it's not pointing to the right commit.

Edit: I also see now that the tag 4.0.8 does seem to point to a commit with all of these changes (including version of 4.1.0 in the toml file). Likely this version would work if nixpkgs switched to it.

**Comment by fabiscafe** [comment]
It looks like 
* [tag 4.0.8 ](https://github.com/libkeepass/pykeepass/releases/tag/v4.0.8)points to the [4.1.0 code](https://github.com/libkeepass/pykeepass/commit/56a81595ad93db67dd2a52d45aec411d5fbb2a64)
* [tag 4.1.0](https://github.com/libkeepass/pykeepass/releases/tag/v4.1.0) points to a deleted [4.0.8 code
](https://github.com/libkeepass/pykeepass/commit/1cef39e3ad2163127a8fe928f516b6adb3ba525a)

@Evidlo could you check/clarify this and at best do a "hotfix" release with a new version number and fitting code/tag? hehe :angel:

**Comment by Evidlo** [comment]
Not sure how that happened.  I'm using a new Makefile which automates the tagging/releasing.  Should be fixed in `4.1.0-post1`

**Comment by jrbp** [comment]
Thank you for the fix! Though in the github web ui if I go to switch branches/tags and select 4.1.0-post1 I still get the message:

`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

Browsing what code is shown there it does seem correct (e.g. pyproject.toml has same version as the tag), so maybe this is working as intended despite the github warning?

**Comment by Evidlo** [comment]
I think all is good now.  The Makefile was pushing the tag, but not the commit.  I've deleted that release and created a new release `4.1.0.post1`.

Note to others: setuptools unhelpfully normalizes semver `4.1.0-post1` to `4.1.0.post`.
